from direct.distributed.MsgTypes import *


OTP_DO_ID_SERVER_ROOT = 4007
OTP_DO_ID_FRIEND_MANAGER = 4501
OTP_DO_ID_LEADERBOARD_MANAGER = 4502
OTP_DO_ID_SERVER = 4600
OTP_DO_ID_UBER_DOG = 4601
OTP_CHANNEL_AI_AND_UD_BROADCAST = 4602
OTP_CHANNEL_UD_BROADCAST = 4603
OTP_CHANNEL_AI_BROADCAST = 4604
OTP_NET_MSGR_CHANNEL_ID_ALL_AI = 4605
OTP_NET_MSGR_CHANNEL_ID_UBER_DOG = 4606
OTP_NET_MSGR_CHANNEL_ID_AI_ONLY = 4607
OTP_DO_ID_COMMON = 4615
OTP_DO_ID_GATEWAY = 4616
OTP_DO_ID_TOONTOWN = 4618
OTP_DO_ID_CLIENT_SERVICES_MANAGER = 4665
OTP_DO_ID_TTI_FRIENDS_MANAGER = 4666
OTP_DO_ID_GLOBAL_GROUP_TRACKER = 4478
OTP_DO_ID_CHAT_MANAGER = 4681
OTP_DO_ID_TOONTOWN_AVATAR_MANAGER = 4682
OTP_DO_ID_TOONTOWN_DELIVERY_MANAGER = 4683
OTP_DO_ID_TOONTOWN_TEMP_STORE_MANAGER = 4684
OTP_DO_ID_TOONTOWN_SPEEDCHAT_RELAY = 4712
OTP_DO_ID_SWITCHBOARD_MANAGER = 4685
OTP_DO_ID_AVATAR_FRIENDS_MANAGER = 4686
OTP_DO_ID_PLAYER_FRIENDS_MANAGER = 4687
OTP_DO_ID_CENTRAL_LOGGER = 4688
OTP_DO_ID_TOONTOWN_MAIL_MANAGER = 4690
OTP_DO_ID_TOONTOWN_PARTY_MANAGER = 4691
OTP_DO_ID_TOONTOWN_RAT_MANAGER = 4692
OTP_DO_ID_STATUS_DATABASE = 4693
OTP_DO_ID_TOONTOWN_AWARD_MANAGER = 4694
OTP_DO_ID_TOONTOWN_CODE_REDEMPTION_MANAGER = 4695
OTP_DO_ID_TOONTOWN_IN_GAME_NEWS_MANAGER = 4696
OTP_DO_ID_TOONTOWN_NON_REPEATABLE_RANDOM_SOURCE = 4697
OTP_DO_ID_AI_TRADE_AVATAR = 4698
OTP_DO_ID_TOONTOWN_WHITELIST_MANAGER = 4699
OTP_DO_ID_GUILDS_MANAGER = 4701
OTP_DO_ID_TOONTOWN_CPU_INFO_MANAGER = 4713
OTP_DO_ID_TOONTOWN_SECURITY_MANAGER = 4714
OTP_DO_ID_ZONE_MANAGER = 4950
OTP_ZONE_ID_INVALID = 0
OTP_ZONE_ID_OLD_QUIET_ZONE = 1
OTP_ZONE_ID_MANAGEMENT = 2
OTP_ZONE_ID_DISTRICTS = 3
OTP_ZONE_ID_DISTRICTS_STATS = 4
OTP_ZONE_ID_ELEMENTS = 5
OTP_NET_MESSENGER_CHANNEL = (OTP_DO_ID_UBER_DOG << 32) + OTP_ZONE_ID_MANAGEMENT
OTP_STAFF_CHANNEL = 6200
MESSENGER_CHANNEL_ALL = 17800
MESSENGER_CHANNEL_AI = 17801
MESSENGER_CHANNEL_UD = 17802
dcname2doId = {
    'CentralLogger': OTP_DO_ID_CENTRAL_LOGGER,
    'ClientServicesManager': OTP_DO_ID_CLIENT_SERVICES_MANAGER,
    'ChatAgent': OTP_DO_ID_CHAT_MANAGER,
    'FriendManager': OTP_DO_ID_FRIEND_MANAGER,
    'AvatarFriendsManager': OTP_DO_ID_AVATAR_FRIENDS_MANAGER,
    'PlayerFriendsManager': OTP_DO_ID_PLAYER_FRIENDS_MANAGER,
    'TTIFriendsManager': OTP_DO_ID_TTI_FRIENDS_MANAGER,
    'TTSpeedchatRelay': OTP_DO_ID_TOONTOWN_SPEEDCHAT_RELAY,
    'DistributedDeliveryManager': OTP_DO_ID_TOONTOWN_DELIVERY_MANAGER,
    'DistributedDataStoreManager': OTP_DO_ID_TOONTOWN_TEMP_STORE_MANAGER,
    'DistributedPartyManager': OTP_DO_ID_TOONTOWN_PARTY_MANAGER,
    'TTCodeRedemptionMgr': OTP_DO_ID_TOONTOWN_CODE_REDEMPTION_MANAGER,
    'GuildManager': OTP_DO_ID_GUILDS_MANAGER,
    'GlobalGroupTracker': OTP_DO_ID_GLOBAL_GROUP_TRACKER,
    'ZoneManager': OTP_DO_ID_ZONE_MANAGER
}
