from toontown.toonbase.ToontownGlobals import SellbotFactoryExt, SellbotLobby, CashbotHQ, CashbotLobby,\
    LawbotOfficeExt, LawbotLobby, BossbotHQ, BossbotLobby, OutdoorZone
from toontown.toonbase import TTLocalizer

# Indexes

LEADER_NAME = 0
SHARD_NAME = 1
SHARD_ID = 2
CATEGORY = 3
MEMBER_IDS = 4
MEMBER_NAMES = 5
SHOW = 6
TYPE = 7
ZONE_ID = 8

# Category ID's

SELLBOT_FACTORY_FRONT = 0
SELLBOT_FACTORY_SIDE = 1
SELLBOT_VP = 2

CASHBOT_COIN_MINT = 10
CASHBOT_DOLLAR_MINT = 11
CASHBOT_BULLION_MINT = 12
CASHBOT_CFO = 13

LAWBOT_A_OFFICE = 20
LAWBOT_B_OFFICE = 21
LAWBOT_C_OFFICE = 22
LAWBOT_D_OFFICE = 23
LAWBOT_CJ = 24

BOSSBOT_FRONT_THREE = 30
BOSSBOT_MIDDLE_SIX = 31
BOSSBOT_BACK_NINE = 32
BOSSBOT_CEO = 33

JELLYBEAN_FEST = 34

CORPORATE_STRIKE_OST = 40

CATEGORY_NO_UPDATE = 99

GROUP_TYPE_NORMAL = 0
GROUP_TYPE_JELLYBEAN = 1

SPECIAL_GROUPS = [GROUP_TYPE_JELLYBEAN]

ZONE_TO_CATEGORY_LIST = {
    SellbotFactoryExt: [SELLBOT_FACTORY_FRONT, SELLBOT_FACTORY_SIDE],
    SellbotLobby: [SELLBOT_VP],
    CashbotHQ: [CASHBOT_COIN_MINT, CASHBOT_DOLLAR_MINT, CASHBOT_BULLION_MINT],
    CashbotLobby: [CASHBOT_CFO],
    LawbotOfficeExt: [LAWBOT_A_OFFICE, LAWBOT_B_OFFICE, LAWBOT_C_OFFICE, LAWBOT_D_OFFICE],
    LawbotLobby: [LAWBOT_CJ],
    BossbotHQ: [BOSSBOT_FRONT_THREE, BOSSBOT_MIDDLE_SIX, BOSSBOT_BACK_NINE],
    BossbotLobby: [BOSSBOT_CEO],
    OutdoorZone: [CORPORATE_STRIKE_OST]
}

CATEGORY_TO_ZONE = {
    SELLBOT_FACTORY_FRONT: SellbotFactoryExt,
    SELLBOT_FACTORY_SIDE: SellbotFactoryExt,
    SELLBOT_VP: SellbotLobby,
    CASHBOT_COIN_MINT: CashbotHQ,
    CASHBOT_DOLLAR_MINT: CashbotHQ,
    CASHBOT_BULLION_MINT: CashbotHQ,
    CASHBOT_CFO: CashbotLobby,
    LAWBOT_A_OFFICE: LawbotOfficeExt,
    LAWBOT_B_OFFICE: LawbotOfficeExt,
    LAWBOT_C_OFFICE: LawbotOfficeExt,
    LAWBOT_D_OFFICE: LawbotOfficeExt,
    LAWBOT_CJ: LawbotLobby,
    BOSSBOT_FRONT_THREE: BossbotHQ,
    BOSSBOT_MIDDLE_SIX: BossbotHQ,
    BOSSBOT_BACK_NINE: BossbotHQ,
    BOSSBOT_CEO: BossbotLobby,
    CORPORATE_STRIKE_OST: OutdoorZone
}

CATEGORY_TO_MAX_PLAYERS = {
    SELLBOT_FACTORY_FRONT: 4,
    SELLBOT_FACTORY_SIDE: 4,
    SELLBOT_VP: 8,

    CASHBOT_COIN_MINT: 4,
    CASHBOT_DOLLAR_MINT: 4,
    CASHBOT_BULLION_MINT: 4,
    CASHBOT_CFO: 8,

    LAWBOT_A_OFFICE: 4,
    LAWBOT_B_OFFICE: 4,
    LAWBOT_C_OFFICE: 4,
    LAWBOT_D_OFFICE: 4,
    LAWBOT_CJ: 8,

    BOSSBOT_FRONT_THREE: 4,
    BOSSBOT_MIDDLE_SIX: 4,
    BOSSBOT_BACK_NINE: 4,
    BOSSBOT_CEO: 8,

    CORPORATE_STRIKE_OST: 4,

    JELLYBEAN_FEST: 500
}

CATEGORY_TO_IMAGE_ID = {
    JELLYBEAN_FEST: 4,

    SELLBOT_FACTORY_FRONT: 3,
    SELLBOT_FACTORY_SIDE: 3,
    SELLBOT_VP: 3,

    CASHBOT_COIN_MINT: 2,
    CASHBOT_DOLLAR_MINT: 2,
    CASHBOT_BULLION_MINT: 2,
    CASHBOT_CFO: 2,

    LAWBOT_A_OFFICE: 1,
    LAWBOT_B_OFFICE: 1,
    LAWBOT_C_OFFICE: 1,
    LAWBOT_D_OFFICE: 1,
    LAWBOT_CJ: 1,

    BOSSBOT_FRONT_THREE: 0,
    BOSSBOT_MIDDLE_SIX: 0,
    BOSSBOT_BACK_NINE: 0,
    BOSSBOT_CEO: 0,

    CORPORATE_STRIKE_OST: 0
}

INFORM_COMING = 0
INFORM_NOT_COMING = 1

INFORM_CODE_TO_STRING = {
    INFORM_COMING: TTLocalizer.GroupTrackerInformComing,
    INFORM_NOT_COMING: TTLocalizer.GroupTrackerInformNotComing
}
