from panda3d.core import Point3, Vec3, Vec4
from toontown.effects.FireworkGlobals import FireworkType
from toontown.toonbase import ToontownGlobals
from toontown.parties import PartyGlobals
import random
colors = [Vec4(1, 1, 1, 1),
 Vec4(1, 0.1, 0.1, 1),
 Vec4(0.1, 1, 0.1, 1),
 Vec4(0.3, 1, 0.3, 1),
 Vec4(0.2, 0.2, 1, 1),
 Vec4(1, 1, 0.1, 1),
 Vec4(1, 0.5, 0.1, 1),
 Vec4(1, 0.1, 1, 1),
 Vec4(0.1, 1, 1, 1),
 Vec4(0.1, 0.5, 1, 1)]


def r():
    return random.randint(8, 12) / 10.0


def rV():
    return Vec3(random.randint(-60, 60), random.randint(10, 30), random.randint(125, 150))


def rP():
    return Point3(0, 0, 0)


def rS():
    return 1.0 + random.random() / 2.0


def rC():
    return random.choice(colors)


def rT():
    return random.randint(12, 20) / 10.0


def rD():
    return random.randint(1, 20) / 10.0


showData = {ToontownGlobals.JULY4_FIREWORKS: [[FireworkType.GlowFlare,
                                    Vec3(-90, 0, 80),
                                    Vec3(120, 0, 0),
                                    rS(),
                                    Vec4(1, 1, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    0.0],
                                   [FireworkType.GlowFlare,
                                    Vec3(90, 0, 80),
                                    Vec3(-120, 0, 0),
                                    rS(),
                                    Vec4(1, 1, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    1.0],
                                   [FireworkType.BasicPeony,
                                    Vec3(50, 0, 140),
                                    rP(),
                                    rS(),
                                    Vec4(1, 1, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    rT(),
                                    0.0],
                                   [FireworkType.BasicPeony,
                                    Vec3(-50, 0, 140),
                                    rP(),
                                    rS(),
                                    Vec4(1, 1, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    rT(),
                                    3.0],
                                   [FireworkType.AdvancedPeony,
                                    Vec3(-90, 0, 110),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.25],
                                   [FireworkType.AdvancedPeony,
                                    Vec3(0, 0, 90),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.25],
                                   [FireworkType.AdvancedPeony,
                                    Vec3(90, 0, 110),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    4.0],
                                   [FireworkType.GlowFlare,
                                    Vec3(-90, 0, 80),
                                    Vec3(120, 0, 0),
                                    1.5,
                                    Vec4(1, 1, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    3.0,
                                    3.0],
                                   [FireworkType.Ring,
                                    Vec3(-90, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.2],
                                   [FireworkType.Ring,
                                    Vec3(-30, 0, 100),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.2],
                                   [FireworkType.Ring,
                                    Vec3(30, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.2],
                                   [FireworkType.Ring,
                                    Vec3(90, 0, 100),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    3.0],
                                   [FireworkType.Bees,
                                    Vec3(0, 50, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    2.0],
                                   [FireworkType.TrailBurst,
                                    Vec3(-70, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.25],
                                   [FireworkType.TrailBurst,
                                    Vec3(70, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    3.0],
                                   [FireworkType.DiademPeony,
                                    Vec3(90, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.15],
                                   [FireworkType.DiademPeony,
                                    Vec3(-30, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.15],
                                   [FireworkType.DiademPeony,
                                    Vec3(30, 0, 100),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.15],
                                   [FireworkType.DiademPeony,
                                    Vec3(-90, 0, 100),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    3.0],
                                   [FireworkType.PalmTree,
                                    Vec3(0, 40, 100),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    4.0],
                                   [FireworkType.Chrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.0],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.5],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    3.0],
                                   [FireworkType.Saturn,
                                    Vec3(90, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.0],
                                   [FireworkType.Saturn,
                                    Vec3(-90, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    2.5],
                                   [FireworkType.GlowFlare,
                                    Vec3(0, 0, 90),
                                    Vec3(-120, 0, 0),
                                    rS(),
                                    Vec4(0.1, 0.5, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    1.0],
                                   [FireworkType.GlowFlare,
                                    Vec3(0, 0, 100),
                                    Vec3(-60, 0, 0),
                                    rS(),
                                    Vec4(0.1, 0.5, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    1.0],
                                   [FireworkType.GlowFlare,
                                    Vec3(0, 0, 110),
                                    Vec3(0, 0, 0),
                                    rS(),
                                    Vec4(0.1, 0.5, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    1.0],
                                   [FireworkType.GlowFlare,
                                    Vec3(0, 0, 120),
                                    Vec3(60, 0, 0),
                                    rS(),
                                    Vec4(0.1, 0.5, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    1.0],
                                   [FireworkType.GlowFlare,
                                    Vec3(0, 0, 130),
                                    Vec3(120, 0, 0),
                                    rS(),
                                    Vec4(0.1, 0.5, 1, 1),
                                    Vec4(1, 1, 1, 1),
                                    1.5,
                                    2.0],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.5],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    2.0],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.5],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    2.0],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.5],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    1.0],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    0.5],
                                   [FireworkType.DiademChrysanthemum,
                                    rV(),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    3.0],
                                   [FireworkType.AmericanFlag,
                                    Vec3(0, 0, 230),
                                    Vec3(-50, 0, 0),
                                    rS(),
                                    rC(),
                                    rC(),
                                    rT(),
                                    6],
                                   [FireworkType.DiademPeony,
                                    Vec3(90, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    2.5,
                                    0.15],
                                   [FireworkType.DiademPeony,
                                    Vec3(30, 0, 140),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    2.5,
                                    0.15],
                                   [FireworkType.DiademPeony,
                                    Vec3(-30, 0, 120),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    2.5,
                                    0.15],
                                   [FireworkType.DiademPeony,
                                    Vec3(-90, 0, 140),
                                    rP(),
                                    rS(),
                                    rC(),
                                    rC(),
                                    2.5,
                                    3.0],
                                   [FireworkType.Mickey,
                                    Vec3(0, 0, 100),
                                    rP(),
                                    1.4,
                                    rC(),
                                    rC(),
                                    2.0,
                                    10.0]],
 PartyGlobals.EFireworkShow.SUMMER: [[FireworkType.DiademPeony,
                                      Vec3(90, 0, 120),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.0],
                                     [FireworkType.DiademPeony,
                                      Vec3(0, 0, 70),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.0],
                                     [FireworkType.DiademPeony,
                                      Vec3(-90, 0, 100),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      3.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 130),
                                      Vec3(0, 0, 0),
                                      rS(),
                                      Vec4(0.1, 0.5, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      3.5,
                                      1.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 90),
                                      Vec3(-50, 0, 0),
                                      rS(),
                                      Vec4(0.1, 0.5, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      2.5,
                                      0.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 90),
                                      Vec3(50, 0, 0),
                                      rS(),
                                      Vec4(0.1, 0.5, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      2.5,
                                      2.0],
                                     [FireworkType.DiademChrysanthemum,
                                      Vec3(40, 50, 140),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      1.5],
                                     [FireworkType.DiademChrysanthemum,
                                      Vec3(-40, -50, 140),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      3.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(-90, 0, 80),
                                      Vec3(120, 0, 0),
                                      1.5,
                                      Vec4(1, 1, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      3.0,
                                      5.5],
                                     [FireworkType.DiademChrysanthemum,
                                      Vec3(0, 0, 100),
                                      Vec3(-120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 100),
                                      Vec3(-120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      1.5,
                                      1.0],
                                     [FireworkType.DiademChrysanthemum,
                                      Vec3(0, 0, 100),
                                      Vec3(0, 20, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 100),
                                      Vec3(0, 20, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      1.5,
                                      1.0],
                                     [FireworkType.DiademChrysanthemum,
                                      Vec3(0, 0, 100),
                                      Vec3(120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 100),
                                      Vec3(120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      1.5,
                                      5.0],
                                     [FireworkType.AdvancedPeony,
                                      Vec3(-90, 0, 110),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.25],
                                     [FireworkType.AdvancedPeony,
                                      Vec3(0, 0, 90),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.25],
                                     [FireworkType.AdvancedPeony,
                                      Vec3(90, 0, 110),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      4.0],
                                     [FireworkType.Mickey,
                                      Vec3(70, 0, 120),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      3.0],
                                     [FireworkType.DiademPeony,
                                      Vec3(90, 0, 120),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.15],
                                     [FireworkType.DiademPeony,
                                      Vec3(-30, 0, 120),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.15],
                                     [FireworkType.DiademPeony,
                                      Vec3(30, 0, 100),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.15],
                                     [FireworkType.DiademPeony,
                                      Vec3(-90, 0, 100),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      3.0],
                                     [FireworkType.Bees,
                                      Vec3(0, 0, 100),
                                      rP(),
                                      1.4,
                                      rC(),
                                      rC(),
                                      2.0,
                                      4.0],
                                     [FireworkType.Chrysanthemum,
                                      rV(),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.0],
                                     [FireworkType.DiademChrysanthemum,
                                      rV(),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.DiademChrysanthemum,
                                      rV(),
                                      rP(),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      3.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(200, 0, 180),
                                      Vec3(-60, 0, 0),
                                      rS(),
                                      rC(),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      2.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(150, 10, 180),
                                      Vec3(-60, 0, 0),
                                      rS(),
                                      rC(),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      1.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(100, 20, 180),
                                      Vec3(-60, 0, 0),
                                      rS(),
                                      rC(),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      1.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(50, 30, 180),
                                      Vec3(-60, 0, 0),
                                      rS(),
                                      rC(),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      1.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 40, 180),
                                      Vec3(-60, 0, 0),
                                      rS(),
                                      rC(),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      2.0],
                                     [FireworkType.Saturn,
                                      Vec3(0, 0, 100),
                                      Vec3(-120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 100),
                                      Vec3(-120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      1.5,
                                      1.0],
                                     [FireworkType.Saturn,
                                      Vec3(0, 0, 100),
                                      Vec3(0, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 100),
                                      Vec3(0, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      1.5,
                                      1.0],
                                     [FireworkType.Saturn,
                                      Vec3(0, 0, 100),
                                      Vec3(120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      rT(),
                                      0.5],
                                     [FireworkType.GlowFlare,
                                      Vec3(0, 0, 100),
                                      Vec3(120, 0, 0),
                                      rS(),
                                      rC(),
                                      rC(),
                                      1.5,
                                      5.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(-15, 0, 60),
                                      Vec3(0, 0, 0),
                                      rS(),
                                      Vec4(1, 1, 0.4, 1),
                                      Vec4(1, 1, 1, 1),
                                      2.5,
                                      0.0],
                                     [FireworkType.GlowFlare,
                                      Vec3(15, 0, 60),
                                      Vec3(0, 0, 0),
                                      rS(),
                                      Vec4(1, 1, 0.4, 1),
                                      Vec4(1, 1, 1, 1),
                                      2.5,
                                      0.0],
                                     [FireworkType.IceCream,
                                      Vec3(0, 0, 80),
                                      Vec3(0, 0, 0),
                                      1.0,
                                      Vec4(1, 1, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      0.0],
                                     [FireworkType.IceCream,
                                      Vec3(0, 0, 110),
                                      Vec3(0, 0, 0),
                                      0.6,
                                      Vec4(1, 1, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      0.0],
                                     [FireworkType.IceCream,
                                      Vec3(0, 0, 130),
                                      Vec3(0, 0, 0),
                                      0.3,
                                      Vec4(1, 1, 1, 1),
                                      Vec4(1, 1, 1, 1),
                                      1.5,
                                      10.0]],
 ToontownGlobals.NEWYEARS_FIREWORKS: [[FireworkType.GlowFlare,
                                       Vec3(0, 0, 180),
                                       Vec3(-120, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 120),
                                       Vec3(-60, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 80),
                                       Vec3(-10, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 80),
                                       Vec3(10, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 120),
                                       Vec3(60, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 180),
                                       Vec3(120, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       2.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 80),
                                       Vec3(120, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 120),
                                       Vec3(60, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 180),
                                       Vec3(10, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 180),
                                       Vec3(-10, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 120),
                                       Vec3(-60, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       1.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(0, 0, 80),
                                       Vec3(-120, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       1.5,
                                       2.0],
                                      [FireworkType.GlowFlare,
                                       Vec3(-180, 0, 180),
                                       Vec3(-60, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       2.5,
                                       0.15],
                                      [FireworkType.GlowFlare,
                                       Vec3(180, 0, 180),
                                       Vec3(60, 0, 0),
                                       rS(),
                                       rC(),
                                       Vec4(1, 1, 1, 1),
                                       2.5,
                                       0.15],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(40, 50, 140),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       1.5],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(-40, -50, 140),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       3.0],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(-140, 50, 120),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.25],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(70, -40, 90),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       1.5,
                                       0.25],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(-100, 30, 60),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.25],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(0, 20, 100),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       1.5,
                                       0.25],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(-70, 0, 130),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.5],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(120, 50, 100),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       1.5,
                                       3.5],
                                      [FireworkType.Mickey,
                                       Vec3(70, 0, 120),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       3.5],
                                      [FireworkType.DiademPeony,
                                       Vec3(90, 0, 120),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.15],
                                      [FireworkType.DiademPeony,
                                       Vec3(-30, 0, 120),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.15],
                                      [FireworkType.DiademPeony,
                                       Vec3(30, 0, 100),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.15],
                                      [FireworkType.DiademPeony,
                                       Vec3(-90, 0, 100),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       3.0],
                                      [FireworkType.Chrysanthemum,
                                       rV(),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.15],
                                      [FireworkType.DiademChrysanthemum,
                                       rV(),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.5],
                                      [FireworkType.DiademChrysanthemum,
                                       rV(),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       1.5],
                                      [FireworkType.DiademChrysanthemum,
                                       rV(),
                                       rP(),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       3.0],
                                      [FireworkType.Saturn,
                                       Vec3(0, 0, 100),
                                       Vec3(-120, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.5],
                                      [FireworkType.Saturn,
                                       Vec3(20, 0, 70),
                                       Vec3(-120, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.5],
                                      [FireworkType.DiademPeony,
                                       Vec3(-30, 0, 120),
                                       Vec3(120, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.5],
                                      [FireworkType.DiademPeony,
                                       Vec3(0, 0, 90),
                                       Vec3(120, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       4.0],
                                      [FireworkType.DiademPeony,
                                       Vec3(-140, 50, 120),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       0.25],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(70, -40, 90),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       1.5,
                                       0.25],
                                      [FireworkType.DiademPeony,
                                       Vec3(-100, 30, 60),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       2.25,
                                       0.25],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(0, 20, 100),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       1.5,
                                       2.0],
                                      [FireworkType.DiademPeony,
                                       Vec3(-70, 0, 130),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       rT(),
                                       1.5],
                                      [FireworkType.DiademChrysanthemum,
                                       Vec3(120, 50, 100),
                                       Vec3(0, 0, 0),
                                       rS(),
                                       rC(),
                                       rC(),
                                       1.5,
                                       5.0],
                                      [FireworkType.Bees,
                                       Vec3(0, 0, 100),
                                       rP(),
                                       1.4,
                                       rC(),
                                       rC(),
                                       2.0,
                                       10.0]]}
showData[ToontownGlobals.COMBO_FIREWORKS] = showData[ToontownGlobals.NEWYEARS_FIREWORKS]
sectionData = {ToontownGlobals.JULY4_FIREWORKS: [(0, 24), (24, len(showData[ToontownGlobals.JULY4_FIREWORKS]))],
 PartyGlobals.EFireworkShow.SUMMER: [(0, 24), (24, len(showData[PartyGlobals.EFireworkShow.SUMMER]))],
 ToontownGlobals.NEWYEARS_FIREWORKS: [(0, len(showData[PartyGlobals.EFireworkShow.SUMMER]))],
 ToontownGlobals.COMBO_FIREWORKS: [(0, len(showData[PartyGlobals.EFireworkShow.SUMMER]))]}


def getShowDuration(showType):
    duration = 0.0
    for firework in showData[showType]:
        duration += firework[7]

    return duration
