from direct.fsm.FSM import FSM
from . import PetUtil, PetDNA, PetNameGenerator
from toontown.toonbase import ToontownGlobals
import time
import random
import sys


class PetManagerAI:
    dailyPets = 5

    def __init__(self, air):
        self.air = air
        self.nameGen = PetNameGenerator.PetNameGenerator()

    def getDayId(self):
        return int(time.time() // 86400)

    def generateSeeds(self):
        random.seed(self.air.ourChannel + self.getDayId())
        seeds = [random.randint(0, sys.maxsize) for _ in range(90)]
        random.shuffle(seeds)

        self.seeds = {}
        for hood in (ToontownGlobals.ToontownCentral, ToontownGlobals.DonaldsDock, ToontownGlobals.DaisyGardens,
                     ToontownGlobals.MinniesMelodyland, ToontownGlobals.TheBrrrgh, ToontownGlobals.DonaldsDreamland):
            bldgMgr = self.air.buildingManagers.get(hood)
            if bldgMgr is None:
                continue
            petshopBlocks = bldgMgr.getDNABlockLists()[3]
            petShopBuilding = bldgMgr.getBuilding(petshopBlocks[0])

            for npcId in petShopBuilding.npcIds:
                self.seeds[npcId] = [seeds.pop() for _ in range(self.dailyPets)]

        self.seeds['day'] = self.getDayId()

    def getAvailablePets(self, npcId):
        if self.seeds.get('day', -1) != self.getDayId():
            self.generateSeeds()

        seeds = self.seeds.get(npcId, [])
        while len(seeds) < self.dailyPets:
            # Generate a new one
            self.generateNewSeed(npcId)

        return self.seeds.get(npcId, [])

    def createNewPetFromSeed(self, avId, seed, dna, traitSeed, nameIndex, gender, safeZoneId):
        av = self.air.doId2do[avId]

        name = self.nameGen.getName(nameIndex)

        head, ears, nose, tail, body, color, cs, eye, _ = dna
        numGenders = len(PetDNA.PetGenders)
        gender %= numGenders
        print(('New pet with dna %s and traitSeed %s was generated by %s.' % (dna, traitSeed, avId)))

        fields = {'setOwnerId' : avId, 'setPetName' : name, 'setTraitSeed' : traitSeed, 'setSafeZone' : safeZoneId,
                  'setHead' : head, 'setEars' : ears, 'setNose' : nose, 'setTail' : tail, 'setBodyTexture' : body,
                  'setColor' : color, 'setColorScale' : cs, 'setEyeColor' : eye, 'setGender' : gender}

        def response(doId):
            if not doId:
                self.air.notify.warning("Cannot create pet for %s!" % avId)
                return

            self.air.writeServerEvent('bought-pet', avId, doId)
            av.b_setPetId(doId)

        self.air.dbInterface.createObject(self.air.dbId, self.air.dclassesByName['DistributedPetAI'],
                                          {k: (v,) for k,v in list(fields.items())}, response)

    def generateNewSeed(self, npcId):
        if len(self.seeds[npcId]) != self.dailyPets:
            self.seeds[npcId].append(random.randint(0, sys.maxsize))

    def deleteToonsPet(self, avId):
        av = self.air.doId2do[avId]
        pet = av.getPetId()
        if pet:
            if pet in self.air.doId2do:
                self.air.doId2do[pet].requestDelete()

        av.b_setPetId(0)
