import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, ROOT)

from panda3d.core import ConfigVariableString

from toontown.toonbase import ConfigFiles

parser = argparse.ArgumentParser(
    description="Write the Astron config for a distribution.")
parser.add_argument(
    '--distribution', choices=ConfigFiles.CHOICES, default=ConfigFiles.DEV,
    help="Which distribution's config to read it from. Defaults to dev.")
parser.add_argument(
    '--output', default=os.path.join('astron', 'dev.yml'),
    help='Where to write the file. Defaults to astron/dev.yml.')
args = parser.parse_args()

ConfigFiles.load(ConfigFiles.serverFor(args.distribution))

import yaml

from toontown.server.ServerGlobals import getAstronConfig

config = getAstronConfig(
    version=ConfigVariableString('server-version', 'n/a').getValue())

with open(args.output, 'w') as f:
    f.write('# Generated by scripts/write_astron_config.py. Do not edit:\n'
            '# start-server.sh rewrites it on every run.\n')
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)
