CancelGuildInvitation = 'cancelGuildInvitation'  # Sent when they stopped inviting us to a guild
ClickedNameTag = 'clickedNametag'  # Sent when we click another avatar's name-tag with: [avatar]
CollectibleInventoryUpdated = 'collInventoryUpdated'  # Sent when CI is updated on the Toon with: [category]
ConfigReloaded = 'configReloaded'
FriendsListChanged = 'friendsListChanged'  # Sent when the friends list might need updating
GuildMemberChanged = 'guildMemberChanged'  # Sent when a guild member might need updating on a UI element with: [avId]
GuildError = 'guildError'  # Sent when an error occurs with: [errorId]
GuildInviteResponse = 'guildInviteResponse'  # Avatar sends a response to a guild invite with: [responseInt]
GuildInfoChanged = 'guildInfoChanged'  # Sent when the information for the local guild changes
GuildQuestInfoChanged = 'guildQuestInfoChanged'  # Sent when quest info for a guild changed
GuildsListChanged = 'guildsListChanged'  # Sent when the guilds list might need updating
GotGuildInfo = 'gotGuildInfo'  # Sent when the client receives guild info with: [guildInfo]
GuildCheckNameResp = 'guildCheckNameResp'  # Sent when the server responds to our name check for guild with: [valid]
GotLeaderboardInfo = 'gotLeaderboardInfo'  # Sent when new leaderboard info came in
GroupTrackerResponse = 'GroupTrackerResponse'  # Sent when group tracker got info from the UD
PlayerOnline = 'playerOnline'
PlayerOffline = 'playerOffline'
PetPanelDone = 'petPanelDone'           # Sent when the pet detail panel is loaded
ShardInfoUpdated = 'shardInfoUpdated'  # Sent when district page needs to be updated
StatUpdated = 'statUpdated'  # Sent when a stat is updated on the toon with: [category, objective]
ValentinesDayStart = 'ValentinesDayStart'  # Sent when valentines starts
WakeUp = 'wakeup'  # Sent to tell the toon to not fall asleep
GagSlotEnter = 'gag-slot-enter'  # Gag from inventory being hovered [slot]
GagSlotExit = 'gag-slot-exit'   # Gag from inventory being un-hovered [slot]
GagSlotClick = 'gag-slot-click'   # Gag chosen event [slot]
InventoryChanged = 'inventory-changed'  # Gag Inventory changed
LoadoutChanged = 'loadout-changed' # Gag loadout changed
ChooserPick = 'choose-panel-done'   # Town battle target chooser pick event
ChooserBack = 'choose-panel-back'   # Town battle target chooser back event
WaitPanelBack = 'wait-panel-back'   # Town battle wait panel back event
TownBattleDone = 'town-battle-done'  # Town Battle attack selection event
EQUIP_GAG = 'equip-gag'
PURCHASE_DONE = 'purchaseDone'
BOUGHT_GAG = 'boughtGag'
SHOW_BATTLE_INVENTORY = 'showBattleInventory'
HIDE_BATTLE_INVENTORY = 'hideBattleInventory'
ExitWalk = 'exit-walk'
EnterWalk = 'enter-walk'

